name: flutter_autosize_screen
description: A low-cost Flutter screen adaptation solution
version: 1.2.2
homepage: 'https://github.com/niezhiyang/flutter_autosize_screen'
environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter: null
