name: flutter_autosize_screen
description: A low-cost Flutter screen adaptation solution
version: 1.1.3
homepage: 'https://github.com/niezhiyang/flutter_autosize_screen'
environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: '>=2.0.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter: null
